### ISSUE TITLE
iOS app crashes

### ISSUE THREAD

**Issue by therealkh** [Notificare/notificare-sdk-react-native#15]
iOS application crashes with installed 'react-native-notificare' library. no errors, nothing, just app crashes right after it launches

**Comment by hpinhal** [comment]
Hi @therealkh,

Can you provide us with some context?
- Which SDK version are you using?
- Which React Native version are you using?
- What exception is shown there when you build and run the app via Xcode?

**Comment by therealkh** [comment]
sdk version: latest, I mean, I didn't specified any version, just installed (3.3.0).
RN version: 0.68.2

![Screen Shot 2022-09-21 at 15 46 26](https://user-images.githubusercontent.com/65399389/191485276-7ab95696-7c85-4dae-98ef-b5636c2df78d.png)
![Screen Shot 2022-09-21 at 15 45 38](https://user-images.githubusercontent.com/65399389/191485287-e3448bc6-3ddf-41cd-a49a-0be93e2c3da9.png)
![Screen Shot 2022-09-21 at 15 44 15](https://user-images.githubusercontent.com/65399389/191485289-22c9a4cd-f200-4c89-9010-42c4ed2e0b39.png)
![Screen Shot 2022-09-21 at 15 42 20](https://user-images.githubusercontent.com/65399389/191485299-9a2242dd-132c-4144-a60a-e5c4443e1118.png)

**Comment by therealkh** [comment]
@hpinhal ^^

**Comment by therealkh** [comment]
Sorry, looks like problem was in that NotificareServices.plist wasn't included in Xcode. closing issue.

**Comment by hpinhal** [comment]
Hi @therealkh,

I believe the error is relatively self-explanatory.
Adding a file to a directory does not make it part of the iOS project. For files to be processed by Xcode, they must be added to the xcodeproj. Open the workspace on Xcode, right-click on the project folder and "Add files to ___".
