### ISSUE TITLE
iOS SDK Version

### ISSUE THREAD

**Issue by j-cheung** [Notificare/notificare-sdk-react-native#4]
Hi,

I'm currently trying to use this library in our React Native app, and seems to have successfully implemented receiving notifications and inbox on iOS. 

However, when releasing on testflight, on the dashboard the SDK Version is incorrect, showing our App Version Number instead, e.g. my app version is 2.6.1, SDK version shows 2.6.1 as well, and if I change the app version to 3.0.0, it will show as 3.0.0

Any ideas on how I could fix this?

Thanks.

**Comment by hpinhal** [comment]
Hi @j-cheung,

As mentioned in the support channel, we were able to reproduce the issue and will let you know when it's available.

**Comment by j-cheung** [comment]
> Hi @j-cheung,
> 
> As mentioned in the support channel, we were able to reproduce the issue and will let you know when it's available.

Thanks, do you reckon it would affect the functionalities though?

**Comment by hpinhal** [comment]
Depending on your app version this may cause some functionality to misbehave. 
Considering your version is 2.6.1 you're safe.

Anyhow, we have a patch released planned for Monday which will fix this.
You should update it once available.

**Comment by j-cheung** [comment]
I see, thank you for your quick response!

**Comment by hpinhal** [comment]
Hi @j-cheung,

v3.0.1 has been released containing a fix for this issue on the native side.
I'm closing this issue.

**Comment by j-cheung** [comment]
thanks i will check it out!
