### ISSUE TITLE
react-native-notificare-geo targets play-services-location:21.0.1, but other RN dependencies have a maximum of play-services-location:20.0.0

### ISSUE THREAD

**Issue by CriusNyx** [Notificare/notificare-sdk-react-native#70]
I am trying to integrate react-native-notificare-geo into my react native project. However I am having some trouble because of a dependency collection.

react-native-notificare-geo has a transitive dependency through notificare-geo-gms for com.google.android.gms:play-services-location:21.0.1 on Android.

However react-native-maps has a maximum supported version of com.google.android.gms:play-services-location:20.0.0.

Using a version higher then 20.0.0 causes react-native-maps to trigger a system crash.

Using a version lower then 21.0.1 causes react-native-notificare-geo to cause a system crash.

Could you please help me resolve this conflict.

-RJ

-Edit: It looks like it's react-native-geolocation-services that has a limit on the maximum version it supports.

**Comment by Y-Smirnov** [comment]
Hello @CriusNyx 

It seems like **react-native-maps** is using play-services-location 21.0.1.
Please make sure you are using the latest version.

The **react-native-geolocation-services** has not been updated for a while.
Although this is not related to our SDK, upon examining their documentation and issue section, it appears that you can resolve this by setting the version.

Please follow the link below to their documentation:
https://github.com/Agontuk/react-native-geolocation-service/blob/master/docs/setup.md#android

Also, you may take a look at existing issues, for example:
https://github.com/Agontuk/react-native-geolocation-service/issues/424

**Comment by CriusNyx** [comment]
Thank you so much for the help.

I was able to update react-native-maps, and I substituted react-native-geolocation-services for another dependency.

**Comment by SwhiteMHC** [comment]
@CriusNyx What did you replace react-native-geolocation-services with?
